### ISSUE TITLE
Crash with the Combat Roll mod

### ISSUE THREAD

**Issue by notunused** [SniffVillage/Bren#13]
versions 0.3.0 and above crash when the two mods are loaded (and dependencies)

"Error: java.lang.IllegalArgumentException: Can't find attribute combatroll:count"

crash report:
Description: Unexpected error
java.lang.IllegalArgumentException: Can't find attribute combatroll:count
	at net.minecraft.class_5132.method_26865(class_5132.java:22)
	at net.minecraft.class_5132.method_26862(class_5132.java:28)
	at net.minecraft.class_5131.method_26852(class_5131.java:76)
	at net.minecraft.class_1309.method_26825(class_1309.java:1904)
	at net.combatroll.api.EntityAttributes_CombatRoll.getAttributeValue(EntityAttributes_CombatRoll.java:52)
	at net.combatroll.client.RollManager.tick(RollManager.java:55)
	at net.minecraft.class_310.handler$zzo000$combatroll$tick_TAIL(class_310.java:3059)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by WHY-HAVE-YOU-SUMMONED-ME** [comment]
Probably caused by how the mod implement attributes, more specifically method `createPlayerAttributes()` in PlayerEntityMixin.
