### ISSUE TITLE
testing server error

### ISSUE THREAD

**Issue by DarkRocken** [SniffVillage/Bren#6]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bren'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
at nl.sniffiandros.bren.common.Bren.onInitialize(Bren.java:60) ~[bren-0.2.0-1.20.1.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at nl.sniffiandros.bren.common.Bren.onInitialize(Bren.java:60) ~[bren-0.2.0-1.20.1.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
... 7 more

well me and my gang want to play this mod in our server and we got error like that but the in server but in single player world everything work fine but when we run the server the server got error because of it when we remove it the server work fine
pls tried to make it compatable to play in servers

**Comment by SniffVillage** [comment]
what version of minecraft are you using and do you have the fabric api?

**Comment by DarkRocken** [comment]
> what version of minecraft are you using and do you have the fabric api?

fabric-api-0.91.0+1.20.1

**Comment by DarkRocken** [comment]
> what version of minecraft are you using and do you have the fabric api?

yo you didnt reply to me

**Comment by SniffVillage** [comment]
that's because i have nothing to say yet

**Comment by Sator586** [comment]
Yo thats the best vanila style gun mod i ever seen, but i got the same problem on my server(
I have some questions for you:
- Will you fix it?
- If yes how long will it take?
- Also do you know what caused the problem?
i totaly understand that its very hard to fix and appreciate your work) <3

**Comment by SniffVillage** [comment]
i don't know how long it will take but i'm currently busy irl so idk when i will fix it
